import type { Metadata } from "next";
import { Inter, Nunito, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { PrivacyPolicy } from "./components/PrivacyPolicy";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",  // Changed to avoid duplicate variable name
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Odelia's lil corner of the web",
  description: "generated by big brain, smol hands",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${nunitoSans.variable} ${inter.variable} antialiased min-h-screen`}>
        {children}
        <PrivacyPolicy />
      </body>
    </html>
  );
}